-- Insert Algerian Wilayas (Provinces)
INSERT INTO wilayas (code, "nameAr", "nameFr") VALUES
(1, 'أدرار', 'Adrar'),
(2, 'الشلف', 'Chlef'),
(3, 'الأغواط', 'Laghouat'),
(4, 'أم البواقي', 'Oum El Bouaghi'),
(5, 'باتنة', 'Batna'),
(6, 'بجاية', 'Béjaïa'),
(7, 'بسكرة', 'Biskra'),
(8, 'بئر الشافية', 'Béchar'),
(9, 'بليدة', 'Blida'),
(10, 'البويرة', 'Bouira'),
(11, 'تمنراست', 'Tamanrasset'),
(12, 'تبسة', 'Tébessa'),
(13, 'تلمسان', 'Tlemcen'),
(14, 'الجزائر', 'Alger'),
(15, 'جيجل', 'Jijel'),
(16, 'سطيف', 'Sétif'),
(17, 'سعيدة', 'Saïda'),
(18, 'سكيكدة', 'Skikda'),
(19, 'سيدي بلعباس', 'Sidi Bel Abbès'),
(20, 'قسنطينة', 'Constantine'),
(21, 'المدية', 'Médéa'),
(22, 'مستغانم', 'Mostaganem'),
(23, 'معسكر', 'Mascara'),
(24, 'ورقلة', 'Ouargla'),
(25, 'وهران', 'Oran'),
(26, 'إليزي', 'Illizi'),
(27, 'البرج', 'Bordj Bou Arréridj'),
(28, 'الطارف', 'El Tarf'),
(29, 'تندوف', 'Tindouf'),
(30, 'تيسمسيلت', 'Tissemsilt'),
(31, 'الوادي', 'El Oued'),
(32, 'خنشلة', 'Khenchela'),
(33, 'سوق أهراس', 'Souk Ahras'),
(34, 'تيبازة', 'Tipaza'),
(35, 'مرتيل', 'Mila'),
(36, 'عين الدفلة', 'Aïn Defla'),
(37, 'النعامة', 'Naâma'),
(38, 'عين تيموشنت', 'Aïn Témouchent'),
(39, 'غرداية', 'Ghardaïa'),
(40, 'غليزان', 'Relizane'),
(41, 'تيميمون', 'Timioun'),
(42, 'برج باجي مختار', 'Bordj Baji Mokhtar'),
(43, 'أولاد جلال', 'Ouled Djellal'),
(44, 'بني عباس', 'Béni Abbès'),
(45, 'إن صالح', 'In Salah'),
(46, 'إن قزل', 'In Gall'),
(47, 'تقرت', 'Touggourt'),
(48, 'جانت', 'Djanet');

-- Insert Communes for each Wilaya (Sample - you can expand this)
-- Wilaya 1: Adrar
INSERT INTO communes ("wilayaId", "nameAr", "nameFr") VALUES
(1, 'أدرار', 'Adrar'),
(1, 'أولف', 'Aoulef'),
(1, 'رقان', 'Reggane'),
(1, 'تسابيت', 'Tsabit'),
(1, 'أراويون', 'Araouane');

-- Wilaya 14: Alger (Capital)
INSERT INTO communes ("wilayaId", "nameAr", "nameFr") VALUES
(14, 'الجزائر الوسطى', 'Alger Centre'),
(14, 'الحراش', 'El Harrach'),
(14, 'بن عكنون', 'Ben Aknoun'),
(14, 'الشرقة', 'Cheraga'),
(14, 'درارية', 'Dar El Beida'),
(14, 'الدويرة', 'Douraoua'),
(14, 'الفونتين', 'Fontaine'),
(14, 'حسين داي', 'Hussein Dey'),
(14, 'الكاليتاوس', 'Kouba'),
(14, 'لاروسيفيل', 'Larbi Tébessi'),
(14, 'المحمدية', 'Mohammadia'),
(14, 'الموسى', 'Mousseya'),
(14, 'النعامة', 'Naamaoua'),
(14, 'أوليد فاريس', 'Ouled Fayet'),
(14, 'الرايس حميدو', 'Rais Hamidou'),
(14, 'الرويبة', 'Rouiba'),
(14, 'سيدي موسى', 'Sidi Moussa'),
(14, 'سيدي مسعود', 'Sidi M''Cid'),
(14, 'الطاهير', 'Taher'),
(14, 'تيبازة', 'Tipaza'),
(14, 'زرالدة', 'Zeralda');

-- Wilaya 25: Oran
INSERT INTO communes ("wilayaId", "nameAr", "nameFr") VALUES
(25, 'وهران', 'Oran'),
(25, 'أرزيو', 'Arzew'),
(25, 'البطيوة', 'Béthioua'),
(25, 'بوتليليس', 'Boutlelis'),
(25, 'الدشيرة', 'Dahra'),
(25, 'الدرقاوية', 'Dar El Beida'),
(25, 'غنية', 'Gdyel'),
(25, 'حسين داي', 'Hassi Bounif'),
(25, 'إيرليسين', 'Iles'),
(25, 'كرسيم', 'Kerguent'),
(25, 'لاموريسيير', 'Lamur'),
(25, 'مسرغين', 'Messerghin'),
(25, 'مستغانم', 'Misserghine'),
(25, 'نويدرات', 'Nouadhibou'),
(25, 'سيدي الشيخ', 'Sidi Chami'),
(25, 'سيدي ترجي', 'Sidi Triki'),
(25, 'تاجراونة', 'Tadjenanet'),
(25, 'تلمسان', 'Tlemcen'),
(25, 'توتة', 'Tout');

-- Wilaya 20: Constantine
INSERT INTO communes ("wilayaId", "nameAr", "nameFr") VALUES
(20, 'قسنطينة', 'Constantine'),
(20, 'عين أبيض', 'Ain Abid'),
(20, 'عين سمارة', 'Ain Smara'),
(20, 'الخروب', 'El Khroub'),
(20, 'حمة بوزيان', 'Hamma Bouziane'),
(20, 'إبن زياد', 'Ibn Ziad'),
(20, 'مسيلة', 'Messila'),
(20, 'نشمية', 'Nachmia'),
(20, 'سيدي أمبارك', 'Sidi Ambar'),
(20, 'سيدي مرسلي', 'Sidi Merouane'),
(20, 'سيدي ناجي', 'Sidi Naji'),
(20, 'سيدي عزيز', 'Sidi Rezine'),
(20, 'تاجنة', 'Taguine'),
(20, 'تاهاقة', 'Tahakaet'),
(20, 'الطاهير', 'Taliouine'),
(20, 'تيمقاد', 'Timgad'),
(20, 'زيغود يوسف', 'Zighoud Youcef');

-- Add more communes for other wilayas as needed
-- This is a sample - you can expand with more communes for each wilaya
